/* 
 This file was generated by Dashcode.  
 You may edit this file to customize your widget or web page 
 according to the license.txt file included in the project.
 */

//
// Function: load()
// Called by HTML body element's onload event when the web application is ready to start
//

var TeamName1;
var TeamPoints1;

function setupLogic()
{
    TeamName1="Not Yet Picked";
    TeamPoints1=0;
}

function SalamanderSetup()
{
    TeamName1="Salamander";
    TeamPoints1=0;
}