/* 
 This file was generated by Dashcode.  
 You may edit this file to customize your widget or web page 
 according to the license.txt file included in the project.
 */

//
// Function: load()
// Called by HTML body element's onload event when the web application is ready to start
//
function load()
{
    dashcode.setupParts();
    detailTest();
    setupLogic();
}

function detailTest(event)
{
document.getElementById("stackLayout").object.setCurrentView("Team1", false);
}

function NextTeamSwitch(event)
{
document.getElementById("stackLayout").object.setCurrentView("Team2", false);
}

function BeginGame(event)
{
document.getElementById("stackLayout").object.setCurrentView("Scoreboard", false);
WriteScores();
}

function LoadQuestion1(event)
{
document.getElementById("stackLayout").object.setCurrentView("Main", false);
}

function PickCstTeam1(event)
{
document.getElementById("TeamPicker").object.setCurrentView("CustomTeam1", false);
}

function PickCstTeam2(event)
{
document.getElementById("TeamPicker1").object.setCurrentView("view2", false);
}

function LoadMain(event)
{
document.getElementById("stackLayout").object.setCurrentView("Main", false);
}

function Reset()
{
window.location.reload()
}

//
// Gamelogic.js
// The way that the game actually works
//

var TeamName1;
var TeamPoints1;
var TeamName2;
var TeamPoints2;

function setupLogic()
{
    TeamName1 = "Not Yet Picked";
    TeamPoints1=0;
    TeamName2 = "Not Yet Picked";
    TeamPoints2=0;
    // Values you provide
    document.getElementById("TeamStringUI").innerText = TeamName1;
    document.getElementById("button6").object.setEnabled(false);
    document.getElementById("button15").object.setEnabled(false);
}

function SalamanderSetup()
{
    TeamName1="Salamander";
    TeamPoints1=0;
    document.getElementById("TeamStringUI").innerText = TeamName1;
    document.getElementById("salpick1").object.setText("Picked");
    document.getElementById("salpick2").object.setEnabled(false);
    document.getElementById("greenpick1").object.setEnabled(false);
    document.getElementById("homepick1").object.setEnabled(false);
    document.getElementById("custom1").object.setEnabled(false);
    document.getElementById("button6").object.setEnabled(true);
}

function HomelessSetup()
{
    TeamName1="Homeless Helpers";
    TeamPoints1=0;
    document.getElementById("TeamStringUI").innerText = TeamName1;
    document.getElementById("homepick1").object.setText("Picked");
    document.getElementById("salpick1").object.setEnabled(false);
    document.getElementById("homepick2").object.setEnabled(false);
    document.getElementById("greenpick1").object.setEnabled(false);
    document.getElementById("custom1").object.setEnabled(false);
    document.getElementById("button6").object.setEnabled(true);
}

function GreenSetup()
{
    TeamName1="Green Team";
    TeamPoints1=0;
    document.getElementById("TeamStringUI").innerText = TeamName1;
    document.getElementById("salpick1").object.setEnabled(false);
    document.getElementById("greenpick2").object.setEnabled(false);
    document.getElementById("homepick1").object.setEnabled(false);
    document.getElementById("custom1").object.setEnabled(false);
    document.getElementById("button6").object.setEnabled(true);
}

function CustomSetup()
{
    var textBox1 = document.getElementById("CustNameField");
    var CustName1 = textBox1.value;
    TeamName1 = CustName1;
    TeamPoints1 = 0;
    document.getElementById("TeamStringUI").innerText = TeamName1;
    document.getElementById("custompick1").object.setText("Picked");
    document.getElementById("salpick1").object.setEnabled(false);
    document.getElementById("greenpick1").object.setEnabled(false);
    document.getElementById("custom1").object.setEnabled(false);
    document.getElementById("homepick1").object.setEnabled(false);
    document.getElementById("button6").object.setEnabled(true);
}

function CustomSetup2()
{
    var textBox2 = document.getElementById("CustNameField2");
    var CustName2 = textBox2.value;
    TeamName2 = CustName2;
    TeamPoints2 = 0;
    document.getElementById("custompick2").object.setText("Picked");
    document.getElementById("salpick2").object.setEnabled(false);
    document.getElementById("greenpick2").object.setEnabled(false);
    document.getElementById("custom2").object.setEnabled(false);
    document.getElementById("homepick2").object.setEnabled(false);
    document.getElementById("button15").object.setEnabled(true);
}

function GreenSetup2()
{
    TeamName2="Green Team";
    TeamPoints2=0;
    document.getElementById("TeamStringUI").innerText = TeamName1;
    document.getElementById("salpick2").object.setEnabled(false);
    document.getElementById("homepick2").object.setEnabled(false);
    document.getElementById("custom2").object.setEnabled(false);
    document.getElementById("button15").object.setEnabled(true);
}

function HomelessSetup2()
{
    TeamName2="Homeless Helpers";
    TeamPoints2=0;
    document.getElementById("TeamStringUI").innerText = TeamName1;
    document.getElementById("salpick2").object.setEnabled(false);
    document.getElementById("greenpick2").object.setEnabled(false);
    document.getElementById("custom2").object.setEnabled(false);
    document.getElementById("button15").object.setEnabled(true);
}
//
// Scoreboard.js
// Keeps Score
//

function WriteScores()
{
    document.getElementById("Team1Scr").innerText = TeamName1;
    document.getElementById("Team2Scr").innerText = TeamName2;
    document.getElementById("Team1Num").innerText = TeamPoints1;
    document.getElementById("Team2Num").innerText = TeamPoints2;
}

//
// QA.js
// Question logic control
//
function correctAnswer(i)
{
    if(i == 1)
    {
        return new Array("checkbox2","checkbox6");
    }
    if(i == 2)
    {
        return new Array("checkbox11","checkbox12","checkbox23","checkbox24");
    }
    if(i == 3)
    {
        return new Array("checkbox26");
    }
    if(i == 4)
    {
        return new Array("checkbox27");
    }
    if(i == 5)
    {
        return new Array("checkbox28");
    }
     if(i == 6)
    {
        return new Array("checkbox30");
    }
    
}
function checkAnswer(i, s)
{
    for(j=0;j<correctAnswer(i).length;j++)
    {
        if(s == correctAnswer(i)[j])
        {
            return true;
        }
    }
}
function checkArray(i,array)
{
    if(array.length < correctAnswer(i).length)
    {
        return false;
    }
    for(j=0;j<array.length;j++)
    {
        if(!array[j])
        {
            return false;
        }
    }
    return true;
}
function Question1()
{
    doQuestion(1,0,9);
    button3.onclick = nextquestion();
}
function Question2()
{
    doQuestion(2,9,26);
    button4.onclick = nextquestion();
}
function Question3()
{
    doQuestion(3,26,27);
    button5.onclick = nextquestion();
}
function Question4()
{
    doQuestion(3,27,28);
    button7.onclick = nextquestion();
}
function Question5()
{
    doQuestion(3,28,29);
    button11.onclick = nextquestion();
}
function Question6()
{
    doQuestion(3,29,31);
    button13.onclick = nextquestion();
}
var Q1PTS=0;
function doQuestion(qID,boxStart,boxEnd)
{
    // Values you provide
    var correct = [];
    var wrong = false;
    for(i=boxStart;i<boxEnd;i++)
    {
        var id = "checkbox";
        if(i != 0)
        {
            id = id+i;
        }
        var checkbox = document.getElementById(id);	// replace with ID of checkbox
        var checkboxValue = checkbox.firstElementChild.checked;
        if(checkboxValue && !checkAnswer(qID,id))
        {
            correct.push(false);
            wrong = true;
        }
        if(checkboxValue && checkAnswer(qID,id) && !wrong)
        {
            correct.push(true);
        }
    }
     document.getElementById("Text1").innerText = checkArray(qID,correct);
    if(checkArray(qID,correct))
    {
        AddtoPTS()
    }
}

function AddtoPTS()
{
    Q1PTS=Q1PTS+1;
    alert(Q1PTS);
}

var QTScount=1;
function nextquestion()
{
QTScount=QTScount+1;
var currentquestion="Question"+QTScount;
document.getElementById("RenderQuestion").object.setCurrentView(currentquestion, false);
}