/* 
 This file was generated by Dashcode.  
 You may edit this file to customize your widget or web page 
 according to the license.txt file included in the project.
 */

//
// Function: load()
// Called by HTML body element's onload event when the web application is ready to start
//
function load()
{
    dashcode.setupParts();
    detailTest();
}

function detailTest(event)
{
document.getElementById("stackLayout").object.setCurrentView("Team1", false);
}

function NextTeamSwitch(event)
{
document.getElementById("stackLayout").object.setCurrentView("Team2", false);
}

function BeginGame(event)
{
document.getElementById("stackLayout").object.setCurrentView("Ready", false);
}

function PickCstTeam1(event)
{
document.getElementById("TeamPicker").object.setCurrentView("CustomTeam1", false);
}

function LoadMain(event)
{
document.getElementById("stackLayout").object.setCurrentView("Main", false);
}